#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
# global settings
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config window_origin_display       default
yabai -m config window_placement            second_child
yabai -m config window_topmost              off
yabai -m config window_shadow               off
yabai -m config insert_feedback_color       0xaaa6e3a1
yabai -m config active_window_border_color  0xFF7AA2F7
yabai -m config normal_window_border_color  0x0024283B
yabai -m config window_border_width         4         
yabai -m config window_border_radius        12        
yabai -m config window_border_blur          off        
yabai -m config window_border_hidpi         off       
yabai -m config window_border               off      
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                off
yabai -m config mouse_modifier              ctrl
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap
yabai -m config window_shadow               float
yabai -m config window_opacity              off
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
# general space settings
yabai -m config layout                      bsp
yabai -m config top_padding                 12
yabai -m config bottom_padding              12
yabai -m config left_padding                12
yabai -m config right_padding               12
yabai -m config window_gap                  12


yabai -m rule --add label="iTerm2" app="^iTerm2$" title="Visor" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="System Information" app="System Information" title="System Information" manage=off
yabai -m rule --add title="\bLittle Arc\b" manage=off sticky=true

borders active_color=0xff8AADF4 inactive_color=0xff1A1B26 width=6.0 2>/dev/null 1>&2 &
echo "yabai configuration loaded.."
