#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config height                      35
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Firacode Nerd Font:Bold:14.0"
spacebar -m config icon_font                   "Firacode Nerd Font:Bold:16.0"
spacebar -m config background_color            0xff1C1C27
spacebar -m config foreground_color            0xffD1D5DB 
spacebar -m config power_icon_color            0xff52f290
spacebar -m config battery_icon_color          0xff9DD48F
spacebar -m config dnd_icon_color              0xffBE96F0
spacebar -m config clock_icon_color            0xffEBCE99
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  •
spacebar -m config space_icon_color            0xff7FA3EE
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
spacebar -m config space_icon_strip                                  
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%d/%m/%y %r"
spacebar -m config right_shell                 on
spacebar -m config right_shell_icon            
spacebar -m config right_shell_command         "echo $(osascript -e 'set ovol to output volume of (get volume settings)')%"

echo "spacebar configuration loaded.."
